version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9191:9191"
    container_name: app
    depends_on:
      - db
      - kafka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/theride_db
      - SPRING_DATASOURCE_USERNAME=theride
      - SPRING_DATASOURCE_PASSWORD=KfiwSDrL6VPP2s5
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092  # Kafka bootstrap servers

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      POSTGRES_DB: theride_db
      POSTGRES_USER: theride
      POSTGRES_PASSWORD: KfiwSDrL6VPP2s5

  kafka:
    image: 'confluentinc/cp-kafka:latest'  # Use the Confluent Kafka image
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  zookeeper:
    image: 'wurstmeister/zookeeper:3.4.6'
    container_name: zookeeper
    ports:
      - "2181:2181"